/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IJPYCQuizRewardNFTSourceInterface extends ethers.utils.Interface {
  functions: {
    "getQuizEligiblity()": FunctionFragment;
    "getTokenURIJson(uint256,string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getQuizEligiblity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenURIJson",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getQuizEligiblity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenURIJson",
    data: BytesLike
  ): Result;

  events: {};
}

export class IJPYCQuizRewardNFTSource extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IJPYCQuizRewardNFTSourceInterface;

  functions: {
    getQuizEligiblity(overrides?: CallOverrides): Promise<[boolean, number]>;

    getTokenURIJson(
      tokenId_: BigNumberish,
      name_: string,
      originalMinter_: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getQuizEligiblity(overrides?: CallOverrides): Promise<[boolean, number]>;

  getTokenURIJson(
    tokenId_: BigNumberish,
    name_: string,
    originalMinter_: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getQuizEligiblity(overrides?: CallOverrides): Promise<[boolean, number]>;

    getTokenURIJson(
      tokenId_: BigNumberish,
      name_: string,
      originalMinter_: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getQuizEligiblity(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenURIJson(
      tokenId_: BigNumberish,
      name_: string,
      originalMinter_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getQuizEligiblity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenURIJson(
      tokenId_: BigNumberish,
      name_: string,
      originalMinter_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
