/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface QuizRewardNFTTemplateInterface extends ethers.utils.Interface {
  functions: {
    "getTokenURIJson(uint256)": FunctionFragment;
    "qrCode()": FunctionFragment;
    "setQrCode(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTokenURIJson",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "qrCode", values?: undefined): string;
  encodeFunctionData(functionFragment: "setQrCode", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getTokenURIJson",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "qrCode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setQrCode", data: BytesLike): Result;

  events: {};
}

export class QuizRewardNFTTemplate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: QuizRewardNFTTemplateInterface;

  functions: {
    getTokenURIJson(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    qrCode(overrides?: CallOverrides): Promise<[string]>;

    setQrCode(
      _qrCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getTokenURIJson(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  qrCode(overrides?: CallOverrides): Promise<string>;

  setQrCode(
    _qrCode: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getTokenURIJson(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    qrCode(overrides?: CallOverrides): Promise<string>;

    setQrCode(_qrCode: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getTokenURIJson(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    qrCode(overrides?: CallOverrides): Promise<BigNumber>;

    setQrCode(
      _qrCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTokenURIJson(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    qrCode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setQrCode(
      _qrCode: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
