/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AbstractJPYCQuizRewardNFTSource,
  AbstractJPYCQuizRewardNFTSourceInterface,
} from "../AbstractJPYCQuizRewardNFTSource";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidCaller_",
        type: "address",
      },
    ],
    name: "InvalidCaller",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidEligibleCaller_",
        type: "address",
      },
    ],
    name: "InvalidEligibleCaller",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousEligibleCaller_",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newEligibleCaller_",
        type: "address",
      },
    ],
    name: "EligibleCallerTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "getQuizEligiblity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "enum IJPYCQuizCommon.QuizStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "name_",
        type: "string",
      },
      {
        internalType: "address",
        name: "originalMinter_",
        type: "address",
      },
    ],
    name: "getTokenURIJson",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newElilgibleCaller_",
        type: "address",
      },
    ],
    name: "transferEligibleCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AbstractJPYCQuizRewardNFTSource__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractJPYCQuizRewardNFTSourceInterface {
    return new utils.Interface(
      _abi
    ) as AbstractJPYCQuizRewardNFTSourceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbstractJPYCQuizRewardNFTSource {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AbstractJPYCQuizRewardNFTSource;
  }
}
