/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AbstractJPYCQuizAccessControl,
  AbstractJPYCQuizAccessControlInterface,
} from "../AbstractJPYCQuizAccessControl";

const _abi = [
  {
    inputs: [],
    name: "EligibleTargetDoesNotExist",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidAddress_",
        type: "address",
      },
    ],
    name: "InvalidAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidCaller_",
        type: "address",
      },
      {
        internalType: "address",
        name: "eligibleCaller_",
        type: "address",
      },
    ],
    name: "InvalidCaller",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidEligibleCaller_",
        type: "address",
      },
    ],
    name: "InvalidEligibleCaller",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidEligibleTarget_",
        type: "address",
      },
    ],
    name: "InvalidEligibleTarget",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousEligibleCaller_",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newEligibleCaller_",
        type: "address",
      },
    ],
    name: "SetEligibleCaller",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousEligibleTarget_",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newEligibleTarget_",
        type: "address",
      },
    ],
    name: "SetEligibleTarget",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newElilgibleCaller_",
        type: "address",
      },
    ],
    name: "setEligibleCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newElilgibleTarget_",
        type: "address",
      },
    ],
    name: "setEligibleTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class AbstractJPYCQuizAccessControl__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractJPYCQuizAccessControlInterface {
    return new utils.Interface(_abi) as AbstractJPYCQuizAccessControlInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbstractJPYCQuizAccessControl {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AbstractJPYCQuizAccessControl;
  }
}
