/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJPYCQuizRewardNFT,
  IJPYCQuizRewardNFTInterface,
} from "../IJPYCQuizRewardNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "destination_",
        type: "address",
      },
    ],
    name: "mintFromRewardCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJPYCQuizRewardNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IJPYCQuizRewardNFTInterface {
    return new utils.Interface(_abi) as IJPYCQuizRewardNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJPYCQuizRewardNFT {
    return new Contract(address, _abi, signerOrProvider) as IJPYCQuizRewardNFT;
  }
}
