/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJPYCQuizCommon,
  IJPYCQuizCommonInterface,
} from "../IJPYCQuizCommon";

const _abi = [
  {
    inputs: [],
    name: "getQuizEligiblity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "enum IJPYCQuizCommon.QuizStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IJPYCQuizCommon__factory {
  static readonly abi = _abi;
  static createInterface(): IJPYCQuizCommonInterface {
    return new utils.Interface(_abi) as IJPYCQuizCommonInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJPYCQuizCommon {
    return new Contract(address, _abi, signerOrProvider) as IJPYCQuizCommon;
  }
}
