/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IJPYCQuizEligibility,
  IJPYCQuizEligibilityInterface,
} from "../IJPYCQuizEligibility";

const _abi = [
  {
    inputs: [],
    name: "getQuizEligiblity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "enum IJPYCQuizEligibility.QuizStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IJPYCQuizEligibility__factory {
  static readonly abi = _abi;
  static createInterface(): IJPYCQuizEligibilityInterface {
    return new utils.Interface(_abi) as IJPYCQuizEligibilityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJPYCQuizEligibility {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IJPYCQuizEligibility;
  }
}
