/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TJPYCQuizRewardNFTSrouce,
  TJPYCQuizRewardNFTSrouceInterface,
} from "../TJPYCQuizRewardNFTSrouce";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "destination_",
        type: "address",
      },
    ],
    name: "mintFromRewardCaller",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TJPYCQuizRewardNFTSrouce__factory {
  static readonly abi = _abi;
  static createInterface(): TJPYCQuizRewardNFTSrouceInterface {
    return new utils.Interface(_abi) as TJPYCQuizRewardNFTSrouceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TJPYCQuizRewardNFTSrouce {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TJPYCQuizRewardNFTSrouce;
  }
}
